locale = "ja"
label = "日本語"
displayName = "日本語"
weight = 1
title = "Sesame blog"
description = "Sesame Tech Blog"
copyright = "© 2026 sesame"

[author]
  name = "sesame"
  headline = "Software Engineer / Developer"
  bio = "Software Engineer exploring AI, Container Architecture & Modern Web."
  links = [
    { github = "https://github.com/sesame" },
  ]
