# -- Language Configuration (ja) --

locale = "ja"
label = "日本語"
displayName = "日本語"
weight = 1
title = "Sesame blog"
description = "開発や検証の技術メモ・備忘録"
copyright = "© 2026 sesame"

[author]
  name = "sesame"
  link = "https://github.com/sesame"
