# -- Markup --
[goldmark]
  [goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
    [goldmark.parser.attribute]
      block = true
  [goldmark.renderer]
    unsafe = true
  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4

[asciidocExt]
  backend = 'html5'
  preserveTOC = true
  [asciidocExt.attributes]
    source-highlighter = 'rouge'
    source-linenums-option = ''
    icons = 'font'
    toc = 'auto'
    toc-title = '目次'
    toclevels = '3'
