baseURL = 'https://sesame.purplemoon.org/'
defaultContentLanguage = 'ja'
locale = 'ja-jp'
title = 'Sesame blog'
theme = 'hugo-coder'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  author = "sesame"
  info = "Software Engineer / Developer"
  description = "Sesame Blog"
  keywords = "blog,developer,personal"
  dateFormat = "2006-01-02"

  # カラーテーマ（auto / dark / light）
  colorScheme = "auto"
  hideColorSchemeToggle = false

  # カスタムCSS & JS
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

# ヘッダーナビゲーションメニュー
[[menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"

[security.exec]
  allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^node$', '^postcss$', '^tailwindcss$', '^asciidoctor$']

[markup.asciidocExt]
  backend = 'html5'
  preserveTOC = true
  [markup.asciidocExt.attributes]
    source-highlighter = 'rouge'
    source-linenums-option = ''
    icons = 'font'
    toc = 'auto'
    toc-title = '目次'
    toclevels = '3'
